# Generated by Django 2.2 on 2019-09-29 16:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('adresse', models.CharField(max_length=250, verbose_name='adress')),
                ('telephone', models.CharField(max_length=8, verbose_name='phone number')),
                ('ville', models.CharField(max_length=100, verbose_name='city')),
                ('creer', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('payer', models.BooleanField(default=True, verbose_name='paid')),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='discount')),
                ('id_braintree', models.CharField(blank=True, max_length=50, verbose_name='ID')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Commandes', to='coupons.Coupon')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ('-creer',),
            },
        ),
        migrations.CreateModel(
            name='ItemCommande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commandes.Commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_commande', to='shop.Produit')),
            ],
            options={
                'verbose_name': 'Element Commandé',
                'verbose_name_plural': 'Elements Commandés',
            },
        ),
    ]
