# Generated by Django 2.2 on 2019-10-05 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='email',
        ),
    ]
