# Generated by Django 2.2 on 2019-10-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_auto_20191023_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='user',
        ),
        migrations.AddField(
            model_name='commande',
            name='first_name',
            field=models.CharField(default='flavienhugs', max_length=50, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='last_name',
            field=models.CharField(default='Hugs', max_length=50, verbose_name='last name'),
            preserve_default=False,
        ),
    ]
