# Generated by Django 2.2 on 2019-10-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_auto_20191023_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='email',
            field=models.EmailField(default='flavienhgs@gmail.com', max_length=254, verbose_name='e-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
