# Generated by Django 2.2 on 2019-10-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='produit',
        ),
    ]
