# Generated by Django 2.2 on 2019-10-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='pseudo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
