# Generated by Django 2.2 on 2019-10-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191019_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='+225 00 000 000', max_length=8, verbose_name='phone number'),
        ),
    ]
