# Generated by Django 2.2 on 2019-09-29 16:00

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Type de produit')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nom du produit')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description du produit')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente')),
                ('prix_reduit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Prix promo')),
                ('image', models.ImageField(blank=True, upload_to='produits/img/%Y/%m/%d', verbose_name='Ajouter une image')),
                ('thumbnails', models.ImageField(blank=True, upload_to='produits/thumb/%Y/%m/%d', verbose_name='Autres image')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponibilité')),
                ('label', models.CharField(blank=True, choices=[('N', 'badge-new'), ('S', 'badge-sale')], max_length=1, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(default=datetime.datetime.now, verbose_name='Ajouté le')),
                ('categorie', models.ForeignKey(on_delete='models.CASCADE', related_name='produits', to='shop.Categorie')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
