# Generated by Django 2.2 on 2019-10-19 14:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Type de produit')),
                ('slug', models.SlugField(help_text='Unique value for product page URL, created from name.', max_length=200, unique=True)),
                ('meta_keywords', models.CharField(help_text='Comma-delimited set of SEO keywords for meta tag', max_length=200, verbose_name='Meta Keywords')),
                ('meta_description', models.CharField(help_text='Content for description meta tag', max_length=255, verbose_name='Meta Description')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('slug', models.SlugField(help_text='Unique value for product page URL, created from name.', max_length=200, unique=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description du produit')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente')),
                ('prix_reduit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix promo')),
                ('image', models.ImageField(blank=True, upload_to='produits/img/%Y/%m/%d', verbose_name='Ajouter une image')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponibilité')),
                ('label', models.CharField(blank=True, choices=[('N', 'badge-new'), ('S', 'badge-sale')], max_length=1, null=True)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('meta_keywords', models.CharField(help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255)),
                ('meta_description', models.CharField(help_text='Content for description meta tag', max_length=255)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(default=datetime.datetime.now, verbose_name='Ajouté le')),
                ('categorie', models.ManyToManyField(to='shop.Categorie')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ['-name', '-creation'],
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('user_name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=200)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='shop.Produit')),
            ],
        ),
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Pub name')),
                ('pub', models.ImageField(blank=True, upload_to='produits/pub/%Y/%m/%d', verbose_name='pub image')),
                ('categorie', models.ManyToManyField(to='shop.Categorie')),
            ],
            options={
                'verbose_name': 'Publicité',
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(related_name='cluster', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Clusters',
            },
        ),
    ]
