# Generated by Django 2.2 on 2019-10-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='meta_description',
            field=models.CharField(default='audio, automobile, smartphone, tv', help_text='Content for description meta tag', max_length=255, verbose_name='Meta Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorie',
            name='meta_keywords',
            field=models.CharField(default='mobile, smartphone, auto, audio, tv', help_text='Comma-delimited set of SEO keywords for meta tag', max_length=200, verbose_name='Meta Keywords'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(help_text='Unique value for product page URL, created from name.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_reduit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix promo'),
        ),
        migrations.AlterModelTable(
            name='categorie',
            table='categories',
        ),
    ]
