# Generated by Django 2.2 on 2019-10-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ('-name',), 'verbose_name': 'categorie', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-name', '-creation'], 'verbose_name': 'produit', 'verbose_name_plural': 'produits'},
        ),
    ]
