# Generated by Django 2.2 on 2019-10-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom du produit'),
        ),
    ]
