# Generated by Django 2.2 on 2019-10-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191021_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marque',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='marque',
            name='meta_keywords',
        ),
    ]
