# Generated by Django 2.2 on 2019-10-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191006_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='categorie',
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ManyToManyField(to='shop.Categorie'),
        ),
    ]
