# Generated by Django 2.2 on 2019-10-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191006_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produit',
            name='meta_description',
            field=models.CharField(default='smartphone, tv, mode, audio, material scholare', help_text='Content for description meta tag', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='meta_keywords',
            field=models.CharField(default='audio, automobile', help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='slug',
            field=models.SlugField(help_text='Unique value for product page URL, created from name.', max_length=200, unique=True),
        ),
    ]
