# Generated by Django 2.2 on 2019-10-21 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191021_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='marque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Marque'),
        ),
    ]
