# Generated by Django 2.2 on 2019-10-21 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20191021_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marque',
            options={'ordering': ('-name',), 'verbose_name': 'marque', 'verbose_name_plural': 'marques'},
        ),
        migrations.AddField(
            model_name='produit',
            name='marque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Marque'),
        ),
    ]
