# Generated by Django 2.2 on 2019-10-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20191006_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
