# Generated by Django 2.2 on 2019-10-17 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='users',
            field=models.ManyToManyField(related_name='cluster', to=settings.AUTH_USER_MODEL),
        ),
    ]
