# Generated by Django 2.2 on 2019-10-21 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20191021_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='marque',
        ),
    ]
