# Generated by Django 2.2 on 2019-10-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_categorie_marque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='label',
            field=models.CharField(blank=True, choices=[('new', 'badge-new'), ('bestseller', 'badge-sale')], max_length=1, null=True),
        ),
    ]
