# Generated by Django 2.2 on 2019-10-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20191023_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'badge-new'), ('S', 'badge-sale')], max_length=1, null=True),
        ),
    ]
